title: Shravya
description: Notes, projects, and demos on AI, ML, and engineering.
url: "https://shravya258.github.io"
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
